version: "3.2"

services:

  mongodb:
    restart: always
    image: mongo:4.2.8
    ports:
        - "27017:27017"
    volumes:
      - devmongo:/data/db
    networks:
      - db-net

  mysqldb:
    restart: always
    image: mysql:8.0.22
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_HOST: "localhost"
      MYSQL_DATABASE: "sciforum"
      MYSQL_USER: "janithahn"
      MYSQL_PASSWORD: "Hello.php1227"
      MYSQL_ROOT_PASSWORD: "Hello.php1227"
    ports:
      - "3302:3306"
    volumes:
      - devmysqldb:/var/lib/mysql
    networks:
      - db-net

  sciforum-backend:
    restart: always
    container_name: back
    command : bash -c "python check_db.py --service-name mysqldb --ip mysqldb --port 3306 &&
                      python manage.py runserver 0.0.0.0:8000"
    env_file:
      - ./sciforum-backend/settings.ini
    build:
      context: ./sciforum-backend/
      dockerfile: Dockerfile
    ports:
      - "8000:443"
    depends_on:
      - mysqldb
      - mongodb
    networks:
      - db-net

networks:
  db-net:
    driver: bridge

volumes:  
  devmysqldb:
  devmongo: