version: "3.2"

services:

  nginx-certbot:
    restart: unless-stopped
    image: staticfloat/nginx-certbot
    ports:
        - 80:80/tcp
        - 443:443/tcp
    environment:
        CERTBOT_EMAIL: admin@sciforum.tech
        # ENVSUBST_VARS: FQDN
        # FQDN: api.sciforum.tech
    volumes:
      - ./conf.d:/etc/nginx/user.conf.d:ro
      - letsencrypt:/etc/letsencrypt
    depends_on:
      - sciforum-backend

  mongodb:
    restart: always
    image: mongo:4.2.8
    ports:
        - "27017:27017"
    volumes:
      - devmongo:/data/db
    networks:
      - db-net

  # mysqldb:
    # restart: always
    # image: mysql:8.0.22
    # command: --default-authentication-plugin=mysql_native_password
    # environment:
      # MYSQL_HOST: "localhost"
      # MYSQL_DATABASE: "sciforum"
      # MYSQL_USER: "janithahn"
      # MYSQL_PASSWORD: "Hello.php1227"
      # MYSQL_ROOT_PASSWORD: "Hello.php1227"
    # ports:
      # - "3302:3306"
    # volumes:
      # - devmysqldb:/var/lib/mysql
    # networks:
      # - db-net

  redis:
    image: redis:latest
    container_name: redis
    ports:
    - "6379:6379"
    # restart: always
    volumes:
            - ./config/redis.conf:/redis.conf
    command: [ "redis-server", "/redis.conf" ]
    networks:
      - db-net

  sciforum-backend: &sciforum-backend
    restart: always
    # container_name: back
    # command : bash -c "python check_db.py --service-name mysqldb --ip mysqldb --port 3306 && python manage.py runserver 0.0.0.0:8000"
    command: bash -c "python manage.py runserver 0.0.0.0:8000"
    env_file:
      - ./sciforum-backend/settings.ini
    build:
      context: ./sciforum-backend/
      dockerfile: Dockerfile
    ports:
       - "8000:8000"
    depends_on:
      # - mysqldb
      - mongodb
    networks:
      - db-net

  celery-worker:
    <<: *sciforum-backend
    image: sciforum-celeryworker
    depends_on:
      - redis
      - mysqldb
    ports: []
    command: celery -A sciforum worker -l INFO
    links:
      - redis
    networks:
      - db-net

  celery-beat:
    <<: *sciforum-backend
    image: sciforum-celerybeat
    depends_on:
      - redis
      - mysqldb
    ports: []
    command: celery -A sciforum beat -l INFO
    links:
      - redis
    networks:
      - db-net

networks:
  db-net:
    driver: bridge

volumes:  
  # devmysqldb:
  devmongo:
  letsencrypt: